package com.tamimarafat.ferngeist.core.model

/**
 * Delivery status for [ChatMessage]s originating from the local user.
 *
 * Messages loaded from session history or generated by the assistant
 * default to [SENT] and are never transitioned.
 */
enum class MessageDeliveryStatus {
    /** Prompt is queued locally waiting for connectivity. */
    QUEUED,

    /** Prompt has been dispatched to the server and is awaiting acknowledgement. */
    SENDING,

    /** Prompt was successfully delivered and acknowledged by the server. */
    SENT,

    /** Prompt send failed; the user may tap to retry. */
    FAILED,
}
